### PR TITLE
Added API call to fishapi to post scores

### PR DESCRIPTION
**Pull request by Jared-Sprague**

### CODE REVIEW

**Comment by mwcz** [comment]
Can you add a "Save high scores" checkbox that defaults to off?  I'm concerned about merging code that attempts posts to localhost without knowing whether the service actually exists.

**Comment by Jared-Sprague** [comment]
I added that option, but if the service is not available.  It gracefully ignores it and doesn't throw an error.

**Comment by Jared-Sprague** [comment]
BTW here is the rest service: https://github.com/Jared-Sprague/fishapi

**Comment by mwcz** [comment]
:+1:

**Pull request merged**
